In [ ]:
# n-Dimensions
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                      
                    [[7,8,9],
                     [10,11,12]],
                      
                      [[13,14,15],
                      [16,17,18]]]) # --> shape(3,2,3)


#[1,2,3] --> shape(3,)

------------------------------------------------------------------------------
           
[[1,2,3],  
 [4,5,6]]  

--> A matrix, shape: [side:2, elements:3]
    lateral: 2 e  elementos:3
------------------------------------------------------------------------------

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)

--> tensor, shape=(3,2,5)

https://www.tensorflow.org/guide/tensor

In [ ]:
Sequential class
 
tf.keras.Sequential(layers=None, name=None)
 
------------------------------------------------------------------------------
 
model = tf.keras.Sequential()
 
model.add(tf.keras.layers.Dense(8, input_shape=(16,)))
 
model.add(tf.keras.layers.Dense(4))
 
------------------------------------------------------------------------------
 
model = tf.keras.Sequential(
[
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(1)
]
)

------------------------------------------------------------------------------
 

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(784,))
inputs

<tf.Tensor 'input_4:0' shape=(None, 784) dtype=float32>

In [6]:
inputs.shape

TensorShape([None, 784])

In [7]:
inputs.dtype

tf.float32

In [13]:
dense = layers.Dense(64, activation="relu")
x = dense(inputs)
x
dense(keras.Input(shape=(784,)))

<tf.Tensor 'dense_5/Relu_1:0' shape=(None, 64) dtype=float32>

In [12]:
x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(10)(x)
outputs

<tf.Tensor 'dense_4/BiasAdd:0' shape=(None, 10) dtype=float32>

In [15]:
model = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")
model

In [16]:
model.summary()

Model: "mnist_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                650       
Total params: 59,210
Trainable params: 59,210
Non-trainable params: 0
_________________________________________________________________


In [17]:
keras.utils.plot_model(model, "my_first_model.png")

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [ ]:
####################################################################################################
####################################################################################################
####################################################################################################

In [22]:
import tensorflow as tf
from tensorflow import keras

In [20]:
tf.__version__

'2.3.0'

In [21]:
keras.__version__

'2.4.0'

In [23]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [28]:
X_train_full.shape

(60000, 28, 28)

In [30]:
y_train_full.shape

(60000,)

In [33]:
X_test.shape

(10000, 28, 28)

In [34]:
y_test.shape

(10000,)

In [35]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

In [36]:
# 384