In [113]:
# Import Tensor Flow
import tensorflow as  tf
print(tf.__version__)

2.3.0


In [3]:
# Create Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Creater a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7], [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix 

another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
                                            
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                      
                    [[7,8,9],
                     [10,11,12]],
                      
                      [[13,14,15],
                      [16,17,18]]]) # --> shape(3,2,3)


#[1,2,3] --> shape(3,)

#[[1,2,3],
# [1,2,3]] --> shape(2,3)



tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
tensor.ndim

3

In [13]:
# what we`ve got created so far:

# scalar: 1 single number

# vector: a number with direction 

# matrix: a 2-dimensional array of numbers

# tensor: an n-dimensional array of number

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
################################################################
################################################################
################################################################

In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv('plas.csv', index_col=0)
df.head(5)

Entry Molar ratio   T   theory_Mn  Yield     Mn    Mw    DM  DSC  \
Catalyst                                                                       
BMI.In2Cl7      1       1-500  130    1512.00      98  2450  3706  1.51  NaN   
BMI.In2Cl7      2       1-800  130     872.00      98  1498  2207  1.47  NaN   
BMI.In2Cl7      3       1-650  120     726.54      98  1571  1805  1.14  NaN   
BMI.In2Cl7      4       1-650  120     972.50      97  1497  2070  1.38  NaN   
BMI.In2Cl7      5       1-650  120     825.58      97  1515  2130  1.40  NaN   

            cristalinidade  ...  time  mn_110  mw_110   DPI_110  mn_120  \
Catalyst                    ...                                           
BMI.In2Cl7             NaN  ...   2.0   226.0   233.0  1.030973   281.0   
BMI.In2Cl7             NaN  ...   4.0   254.0   281.0  1.106299   313.0   
BMI.In2Cl7             NaN  ...   6.0   221.0   231.0  1.045249   289.0   
BMI.In2Cl7             NaN  ...   8.0   275.0   342.0  1.243636   308.0   
BMI.In2Cl7             NaN  ...  10.0   313.0   365.0  1.166134   422.0   

            mw_120   DPI_120  mn_130  mw_130   DPI_130  
Catalyst                                                
BMI.In2Cl7   784.0  2.790036   430.0   665.0  1.546512  
BMI.In2Cl7   365.0  1.166134   315.0   425.0  1.349206  
BMI.In2Cl7   323.0  1.117647   437.0   649.0  1.485126  
BMI.In2Cl7   390.0  1.266234   484.0   828.0  1.710744  
BMI.In2Cl7   653.0  1.547393   585.0   994.0  1.699145  

[5 rows x 23 columns]

In [57]:
X = df['Mn'].values
y = df['Mw'].values

In [58]:
X,y

(array([2450, 1498, 1571, 1497, 1515, 1196,  818, 2172, 1625, 1105,  810,
        1270,  987,  509, 2115, 1671, 2002, 1275, 2310,  803,  841,  323,
         300,  249,  274,  271,  275,  256], dtype=int64),
 array([3706, 2207, 1805, 2070, 2130, 1884, 1347, 2426, 2745, 1617, 1603,
        2020, 1167,  614, 2654, 2901, 2514, 1741, 2532,  917, 1223,  385,
         352,  257,  297,  283,  284,  258], dtype=int64))

In [59]:
#X = tf.constant(X, dtype=tf.float32)
##X = tf.constant(X)
##y = tf.constant(y)
##X,y

In [60]:
X_tf = tf.cast(tf.constant(X), dtype=tf.float32)
X_tf

<tf.Tensor: shape=(28,), dtype=float32, numpy=
array([2450., 1498., 1571., 1497., 1515., 1196.,  818., 2172., 1625.,
       1105.,  810., 1270.,  987.,  509., 2115., 1671., 2002., 1275.,
       2310.,  803.,  841.,  323.,  300.,  249.,  274.,  271.,  275.,
        256.], dtype=float32)>

In [61]:
y_tf = tf.cast(tf.constant(y), dtype=tf.float32)
y_tf

<tf.Tensor: shape=(28,), dtype=float32, numpy=
array([3706., 2207., 1805., 2070., 2130., 1884., 1347., 2426., 2745.,
       1617., 1603., 2020., 1167.,  614., 2654., 2901., 2514., 1741.,
       2532.,  917., 1223.,  385.,  352.,  257.,  297.,  283.,  284.,
        258.], dtype=float32)>

In [62]:
X_tf,y_tf

(<tf.Tensor: shape=(28,), dtype=float32, numpy=
 array([2450., 1498., 1571., 1497., 1515., 1196.,  818., 2172., 1625.,
        1105.,  810., 1270.,  987.,  509., 2115., 1671., 2002., 1275.,
        2310.,  803.,  841.,  323.,  300.,  249.,  274.,  271.,  275.,
         256.], dtype=float32)>,
 <tf.Tensor: shape=(28,), dtype=float32, numpy=
 array([3706., 2207., 1805., 2070., 2130., 1884., 1347., 2426., 2745.,
        1617., 1603., 2020., 1167.,  614., 2654., 2901., 2514., 1741.,
        2532.,  917., 1223.,  385.,  352.,  257.,  297.,  283.,  284.,
         258.], dtype=float32)>)

In [63]:
#pip install tensorflow

In [64]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [ ]:
@ tf.keras.layers.Dense(1)
@ keras.layers.Dense(units, activation=None, 
@                    use_bias=True, 
@                    kernel_initializer=’glorot_uniform’, 
@                    bias_initializer=’zeros’, 
@                    kernel_regularizer=None, 
@                    bias_regularizer=None, 
@                    activity_regularizer=None, 
@                    kernel_constraint=None, 
@                    bias_constraint=None)
@
@
@
@
@

In [68]:
# Creating a model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1) # Dense(1) one number by one number
])
#model.add(tf.keras.layers.Dense(1))

#           (Dense)
# Input     Hidden    Output
#            O         
#    x       O          P
#    x       O          P
#    x       O          P
#            O

# Compile the model
model.compile(loss=tf.keras.losses.mae, # loss = mean(abs(y_true - y_pred), axis = -1)
             optimizer=tf.keras.optimizers.SGD(), # SGD Gradient Descent
             metrics=['mae'])

# Fit the model
model.fit(X_tf,y_tf, epochs=5)   # The number of epochs is a hyperparameter that defines the number times that the learning algorithm will work through the entire training dataset

# Evaluate the model
#model.evualuate(X_test, y_test)

Epoch 1/5
1/1 [==============================] - 0s 2ms/step - loss: 2771.2332 - mae: 2771.2332
Epoch 2/5
1/1 [==============================] - 0s 1ms/step - loss: 10280.2080 - mae: 10280.2080
Epoch 3/5
1/1 [==============================] - 0s 1000us/step - loss: 2771.2332 - mae: 2771.2332
Epoch 4/5
1/1 [==============================] - 0s 1ms/step - loss: 10280.2080 - mae: 10280.2080
Epoch 5/5
1/1 [==============================] - 0s 1ms/step - loss: 2771.2329 - mae: 2771.2329


In [69]:
model.predict([2450])

array([[25411.793]], dtype=float32)

In [106]:
#########################################

In [70]:
# Let`s see some wasy if we can get a better model.
# Methods to improve the model created.
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(1) # Dense(1) one number by one number
])
#model.add(tf.keras.layers.Dense(1))


# Compile the model
model.compile(loss=tf.keras.losses.mae, # loss = mean(abs(y_true - y_pred), axis = -1)
             optimizer=tf.keras.optimizers.SGD(), # SGD Gradient Descent
             metrics=['mae'])



# Fit the model
model.fit(X_tf, y_tf , epochs=5)   
# The number of epochs is a hyperparameter that defines the number times that the learning algorithm will work through the entire training dataset
# As the number of epochs increases, more number of times the weight are changed in the neural network and the curve goes from underfitting to optimal to overfitting curve.



# Evaluate the model
#model.evualuate(X_test, y_test)

Epoch 1/5
1/1 [==============================] - 0s 1ms/step - loss: 1520.0177 - mae: 1520.0177
Epoch 2/5
1/1 [==============================] - 0s 1ms/step - loss: 62785.7500 - mae: 62785.7500
Epoch 3/5
1/1 [==============================] - 0s 1ms/step - loss: 1569.2500 - mae: 1569.2500
Epoch 4/5
1/1 [==============================] - 0s 1ms/step - loss: 1569.2400 - mae: 1569.2400
Epoch 5/5
1/1 [==============================] - 0s 1ms/step - loss: 1569.2299 - mae: 1569.2299


In [71]:
model.predict([2450])

array([[0.02999999]], dtype=float32)

In [72]:
# Evaluting a model

# Build a model --> fit it --> Evaluate it --> Tweak a model --> fit it 
# --> evaluate it --> tweak it ....

In [73]:
X.shape, y.shape

((28,), (28,))

In [74]:
X,y

(array([2450, 1498, 1571, 1497, 1515, 1196,  818, 2172, 1625, 1105,  810,
        1270,  987,  509, 2115, 1671, 2002, 1275, 2310,  803,  841,  323,
         300,  249,  274,  271,  275,  256], dtype=int64),
 array([3706, 2207, 1805, 2070, 2130, 1884, 1347, 2426, 2745, 1617, 1603,
        2020, 1167,  614, 2654, 2901, 2514, 1741, 2532,  917, 1223,  385,
         352,  257,  297,  283,  284,  258], dtype=int64))

In [75]:
X[0],y[0]

(2450, 3706)

In [76]:
X = tf.constant(X)

y = tf.constant(y)

X, y

(<tf.Tensor: shape=(28,), dtype=int64, numpy=
 array([2450, 1498, 1571, 1497, 1515, 1196,  818, 2172, 1625, 1105,  810,
        1270,  987,  509, 2115, 1671, 2002, 1275, 2310,  803,  841,  323,
         300,  249,  274,  271,  275,  256], dtype=int64)>,
 <tf.Tensor: shape=(28,), dtype=int64, numpy=
 array([3706, 2207, 1805, 2070, 2130, 1884, 1347, 2426, 2745, 1617, 1603,
        2020, 1167,  614, 2654, 2901, 2514, 1741, 2532,  917, 1223,  385,
         352,  257,  297,  283,  284,  258], dtype=int64)>)

In [107]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, input_shape=[1,]),
    tf.keras.layers.Dense(1)
])
                          

#    tf.keras.layers.Dense(50, input_shape=[1])
#])

In [108]:
model.compile(loss=tf.keras.losses.mae,
             optimizer=tf.keras.optimizers.SGD(),
             metrics=["mae"])

In [109]:
#  Model must be created and compiled with the same DistStrat.
# TypeError: Invalid keyword argument(s) in `compile`: {'optmizer'}

In [110]:
model.fit(X,y, epochs=5)

Epoch 1/5
1/1 [==============================] - 0s 1ms/step - loss: 1332.6716 - mae: 1332.6716
Epoch 2/5
1/1 [==============================] - 0s 1ms/step - loss: 75290.8984 - mae: 75290.8984
Epoch 3/5
1/1 [==============================] - 0s 1ms/step - loss: 3966793.7500 - mae: 3966793.7500
Epoch 4/5
1/1 [==============================] - 0s 0s/step - loss: 245458464.0000 - mae: 245458464.0000
Epoch 5/5
1/1 [==============================] - 0s 0s/step - loss: 66565222400.0000 - mae: 66565222400.0000


In [111]:
model.predict([2450])

array([[-8.829751e+12]], dtype=float32)

In [115]:
import tensorflow as tf
from tensorflow import keras

In [116]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

In [118]:
matrix = tf.constant([[10,7,2], 
                      [7,10,5],
                      [7,10,5],
                      [7,10,5],
                      [7,10,5]])

matrix

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[10,  7,  2],
       [ 7, 10,  5],
       [ 7, 10,  5],
       [ 7, 10,  5],
       [ 7, 10,  5]])>

In [ ]:
https://www.google.com/search?q=Flatten+keras&sxsrf=ALeKk00UCB94iWO7GWPdDJeH2sgVr83u6w:1627510421612&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjXjbHk5IbyAhV4HrkGHUgDBzUQ_AUoAXoECAEQAw&biw=1920&bih=969

In [ ]:
https://stackoverflow.com/questions/43237124/what-is-the-role-of-flatten-in-keras